### ISSUE TITLE
MimeMessageViewer error on iOS

### ISSUE THREAD

**Issue by xMonty** [Enough-Software/enough_mail_flutter#8]
i am using MimeMessageViewer to display an email, when the email just has an embedded image (no text) in it and when you tap on it
on android showMediaDelegate is called perfectly 
but on iOS i am getting 
-canOpenURL: failed for URL: "data:text/html;base64,PGh0bWw+PGhlYWQ+PG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9dX ... L2h0bWw+" - error: "This app is not allowed to query for scheme data"

**Comment by robert-virkus** [comment]
Hi Monty,
thanks for the report, do you have a stacktrace for this bug?

**Comment by xMonty** [comment]
A bit more info, 
When i click on an embedded image
in mime_message_viewer.dart
line 200, the uri value is "cid://%3Cii_kn08ztzf0%3E"
i think %3C and %3E are < and > 
therefore 
final cid = requestUri.path; <----- this returns cid as empty
final part = widget.mimeMessage.getPartWithContentId(cid); 
part comes null

dont know if its a bug or the email mime is faulty
thanks for your help

**Comment by robert-virkus** [comment]
Hi Monty, thanks for the additional information, could you post the source of the mime message, too? Please make sure to remove any private information first.

**Comment by robert-virkus** [comment]
Upon considering it again, I believe this is just a problem of handling the content-IDs, the image is visible after all. I have pushed a potential fix, you can check it out by depending directly on git, e.g.
```
dependencies:
  enough_mail_flutter: 
    git:
      url: https://github.com/Enough-Software/enough_mail_flutter.git

```

Can you confirm the fix works?

**Comment by xMonty** [comment]
Unforunately does not work,
requestUri (cid://%3Cii_kn08ztzf0%3E)
final cid = requestUri.path; <- return empty string
here cid is "" (request.Uri returns an empty string)
the checks you applied after is fails as cid is empty before
it is a simple cid issue i think as the image is displayed correctly its just when you tap on it doesnt work

**Comment by robert-virkus** [comment]
ok, stupid me, that wasn't working at all. I'm now doing 3 things:

1. convert the CID to be URL safe in the link (for some reason that also changes the casing in some cases) - this is done in the enough_mail_html package
2. ignore the casing of CIDs in `MimeMessage.getPartWithContentId()` - in the `enough_mail` package
3. use the `requestUri.host` and convert back the CID in the `MimeMessageViewer`

Git contains the fixes, releases of all packagtes are incoming.

**Comment by xMonty** [comment]
Working perfectly now, you can close this bug, also many thanks for your awesome work if i was nearby i would treat you to beers!

**Comment by robert-virkus** [comment]
Haha, my pleasure - thanks for confirming the fix!
